version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Download the SDK Manager
      - wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O sdk-tools.zip
      - unzip sdk-tools.zip -d sdk-tools
      - export ANDROID_SDK_ROOT=$PWD/sdk-tools
      # Install required SDK components
      - yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
      # Accept SDK licenses
      - yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --licenses

build:
  commands:
    # Build the Android app using Gradle
    - ./gradlew assembleDebug

artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
